Table Genero {
  id int [pk, increment]
  nombre varchar(100) [unique, not null]
}

Table Banda {
  id int [pk, increment]
  nombre varchar(100) [unique, not null]
  genero_id int [not null, ref: > Genero.id]
  portada varchar(255) [note: "URL completa de la imagen (ej. https://placehold.co/300x300)", null]
}