# Generated by Django 5.1.4 on 2025-07-24 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('portada', models.URLField(blank=True, help_text='URL completa de la imagen (ej. https://placehold.co/300x300)', null=True)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandas.genero')),
            ],
        ),
    ]
